[server]
maxUploadSize = 25
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#5268F5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F9FD"
textColor = "#15223A"
